In [1]:
import pandas as pd

In [2]:
import os
os.getcwd()

'C:\\Users\\billc'

In [3]:
os.listdir("Downloads")

['(About me) Castilla family picture.jpg',
 '(e6399)_KE_Talent_Handbook_Addendum (1).pdf',
 '(KEY)Equations and Inequalities Study Guide Review (1).pdf',
 '(KEY)Equations and Inequalities Study Guide Review.pdf',
 '- Theoretical & Experimental Probability.pdf',
 '.ipynb_checkpoints',
 '01UwfHrld L._TSa_size_1910,1000_format_(A,f,b,d,pi,pl,o)_b-src_61Cd2rJZgRL.png_b-pos_0,0,1910,1000_pi-src_71wV0-8 4UL.jpg_pi-pos_1000,100,840,840.json',
 '03 Slides_ Your Situation Catalog (1).pdf',
 '03 Slides_ Your Situation Catalog (2).pdf',
 '03 Slides_ Your Situation Catalog.pdf',
 '06 - RATIOS and PROPORTIONS Doodle Math - Interactive Notebooks (Guided Notes).pdf',
 '07 Slides_ Linkedin Part 1 (1).pdf',
 '07 Slides_ Linkedin Part 1.pdf',
 '08 Slides_ LinkedIn Part 2 (1).pdf',
 '08 Slides_ LinkedIn Part 2 (2).pdf',
 '08 Slides_ LinkedIn Part 2.pdf',
 '1 - Proportional vs. Non-Proportional Relationships Mazes.pdf',
 '1 Connect.doc',
 '1- I CAN Checklist-Rates & Ratios.pdf',
 '1-BA Workbook No Answers (1).xlsx',
 '1-BA Workbook No Answers.xlsx',
 '1-Claude Project Cover Letter Rules.pdf',
 '1-Claude Project Resume Rules.pdf',
 '1-Claude Resume Generator Instructions Text.docx',
 '1-Data Cleaning and Prep - Student (1).xlsx',
 '1-Data Cleaning and Prep - Student.xlsx',
 '1-How to Land a Job Without Applying 1.pdf',
 '1-LEFT JOIN Exercises.pdf',
 '1-Microsoft PowerPoint - Week8.pptx (1).pdf',
 '1-Microsoft PowerPoint - Week8.pptx.pdf',
 '1-Prompt Engineering.pdf',
 '1-recent-grads11 (1).csv',
 '1-recent-grads11 (2).csv',
 '1-recent-grads11.csv',
 '1-Subquery Exercises (1).pdf',
 '1-Subquery Exercises (2).pdf',
 '1-Subquery Exercises.pdf',
 '1-The Interview Volume Engine SOP.pdf',
 '1-Week6.pdf',
 '10-Honduras.pptx',
 '11081.pdf',
 '126_EmpHandbook (2).pdf',
 '14147400008995.pdf',
 '15073500013613.pdf',
 '16448500021220.pdf',
 '1bg1yc_bTtiWMOK9yT-2GA_34bc081e5ac4493cbce79de59cb14ee1_Population-Latin-and-Caribbean-Countries-2010-2019.xlsx',
 '1_Formulas_Intro.xlsx',
 '1_Worksheets.xlsx',
 '2-Prompt Engineering.pdf',
 '2-Sample---Superstore--13 (1).csv',
 '2-Sample---Superstore--13 (1).xlsx',
 '2-Sample---Superstore--13 (2).csv',
 '2-Sample---Superstore--13.csv',
 '2017 Intake Form.pdf',
 '2020-03-23 14-47.pdf',
 '20200902_163635.jpg',
 '20201028_174044 (1).jpg',
 '20201028_174044.jpg',
 '20201214_173458 (1).jpg',
 '20201214_173458.jpg',
 '2021-2022-Preschool-Application.doc',
 '2021-2022_Contract_for_Professional_Services_.pdf',
 '20210808_093424.jpg',
 '20211019_210149.jpg',
 '20211021_072108.jpg',
 '20211102_210224 (1).jpg',
 '20211102_210224.jpg',
 '20211102_210246.jpg',
 '20211205_151028.jpg',
 '2021_insurance_summary.pdf',
 '2022-2023 - William Castilla - Preliminary Conference.pdf',
 '2022-2023_Terms_of_Employment_-_William_Casti.pdf',
 '20220623_175251.jpg',
 '2022_insurance_summary.pdf',
 '2023-2024 - William Castilla - Preliminary Conference (1).pdf',
 '2023-2024 - William Castilla - Preliminary Conference.pdf',
 '2_Formatting.xlsx',
 '2_Functions_Intro.xlsx',
 '3-Data Visualization and Storytelling in Excel - Student (1).xlsx',
 '3-Data Visualization and Storytelling in Excel - Student (2).xlsx',
 '3-Data Visualization and Storytelling in Excel - Student (3).xlsx',
 '3-Data Visualization and Storytelling in Excel - Student (4).xlsx',
 '3-Data Visualization and Storytelling in Excel - Student.xlsx',
 '396_Resolving_the_Compound_Effect_of_Poor_Lymphatic_Flow_Heavy_Metals_EMF_and_High_Acidity.mp3',
 '3_Ribbon_Menu.xlsx',
 '5AnglesandTrianglesPrintableExitTickets.pdf',
 '5th_grade_integer_worksheets.pdf',
 '5_Statistical_Functions.xlsx',
 '6.6 Notes -Systems of Inequalities.pdf',
 '6.6 Notes- Systems of Inequalities.pdf',
 '679433102.jpg',
 '679433117.jpg',
 '679683bd-23be-4137-a2b4-00d70fe18cb2.JPG',
 '6thGradeDigitalDailyMathWarmUpforAugSept-1 (1).pdf',
 '6thGradeDigitalDailyMathWarmUpforAugSept-1 (2).pdf',
 '6thGradeDigitalDailyMathWarmUpforAugSept-1 (3).pdf',
 '6thGradeDigitalDailyMathWarmUpforAugSept-1.pdf',
 '6thGradeEndofYearMathReviewJeopardyPREVIEW (1).tiff',
 '6thGradeEndofYearMathReviewJeopardyPREVIEW.tiff',
 '6thGradeMathReviewJeopardyGameTestPrepEndoftheYearFunActivity-1 (1).zip',
 '6thGradeMathReviewJeopardyGameTestPrepEndoftheYearFunActivity-1 (2).zip',
 '6thGradeMathReviewJeopardyGameTestPrepEndoftheYearFunActivity-1 (3).zip',
 '6thGradeMathReviewJeopardyGameTestPrepEndoftheYearFunActivity-1.zip',
 '6thGradeMathSkillsReviewBacktoSchoolFunJeopardyPowerPointGame-1 (1).zip',
 '6thGradeMathSkillsReviewBacktoSchoolFunJeopardyPowerPointGame-1 (2).zip',
 '6thGradeMathSkillsReviewBacktoSchoolFunJeopardyPowerPointGame-1.zip',
 '6thGradeMathWeeklyWarmupsandHomeworkSample-1 (1).pdf',
 '6thGradeMathWeeklyWarmupsandHomeworkSample-1 (2).pdf',
 '6thGradeMathWeeklyWarmupsandHomeworkSample-1 (3).pdf',
 '6thGradeMathWeeklyWarmupsandHomeworkSample-1 (4).pdf',
 '6thGradeMathWeeklyWarmupsandHomeworkSample-1 (5).pdf',
 '6thGradeMathWeeklyWarmupsandHomeworkSample-1 (6).pdf',
 '6thGradeMathWeeklyWarmupsandHomeworkSample-1 (7).pdf',
 '6thGradeMathWeeklyWarmupsandHomeworkSample-1 (8).pdf',
 '6thGradeMathWeeklyWarmupsandHomeworkSample-1 (9).pdf',
 '6thGradeMathWeeklyWarmupsandHomeworkSample-1.pdf',
 '6_Array_Formulas (1).xlsx',
 '6_Array_Formulas.xlsx',
 '7.1  7.2 Quiz (Alg I Cp).pdf',
 '7.1 Notes- Multiplication Properties of Exponents (Alg I Cp).pdf',
 '7.1 Notes- Multiplication Properties of Exponents.pdf',
 '7.1_CP Multiplication Properties (1).notebook',
 '7.1_CP Multiplication Properties (2).notebook',
 '7.1_CP Multiplication Properties.notebook',
 '7.2 Notes-  Division Properties of Exponents.pdf',
 '7.3 Notes- Rational Exponents.pdf',
 '7.3 Notes- Rational Exponents_page_1.pdf',
 '7.3, 7.5, 7.7 Quiz (Alg I Cp) (1).pdf',
 '7.3, 7.5, 7.7 Quiz (Alg I Cp).pdf',
 '7.3, 7.5, 7.7 Quiz.pdf',
 '7.5 Notes- Exponential Functions (1).pdf',
 '7.5 Notes- Exponential Functions.pdf',
 '7th Grade DIGITAL Math BUNDLE _ Google Classroom _ Distance Learning (1).zip',
 '7th Grade DIGITAL Math BUNDLE _ Google Classroom _ Distance Learning (2).zip',
 '7th Grade DIGITAL Math BUNDLE _ Google Classroom _ Distance Learning (3).zip',
 '7th Grade DIGITAL Math BUNDLE _ Google Classroom _ Distance Learning.zip',
 '7th Grade Math Curriculum Common Core Aligned Using Google BUNDLE (1).zip',
 '7th Grade Math Curriculum Common Core Aligned Using Google BUNDLE (2).zip',
 '7th Grade Math Curriculum Common Core Aligned Using Google BUNDLE.zip',
 '7th Grade Math GUIDED NOTES Bundle - Interactive Math Notebooks (BACK TO SCHOOL) (1).zip',
 '7th Grade Math GUIDED NOTES Bundle - Interactive Math Notebooks (BACK TO SCHOOL).zip',
 '7th Grade Reproductive Health (1).pdf',
 '7th Grade Reproductive Health.pdf',
 '7th grade stations update.pdf',
 '7thGradeBackToSchoolMathActivityEscapeRoomReviewof6thGradeSkills-1 (1).pdf',
 '7thGradeBackToSchoolMathActivityEscapeRoomReviewof6thGradeSkills-1 (2).pdf',
 '7thGradeBackToSchoolMathActivityEscapeRoomReviewof6thGradeSkills-1 (3).pdf',
 '7thGradeBackToSchoolMathActivityEscapeRoomReviewof6thGradeSkills-1.pdf',
 '7thGradeBacktoSchoolMathMysteryActivityCSIMathReviewGame-1 (1).zip',
 '7thGradeBacktoSchoolMathMysteryActivityCSIMathReviewGame-1.zip',
 '7thGradeExpressionsEquationsandInequalitiesMathUnitUsingGoogle-1 (1).pdf',
 '7thGradeExpressionsEquationsandInequalitiesMathUnitUsingGoogle-1.pdf',
 '7thGradeFractionsDecimalsandOrderofOperationsReviewUnitUsingGoogle-1.pdf',
 '7thGradeGEOMETRYMathUnitUsingGoogleforDistanceLearning-1.pdf',
 '7thGradeIntegersandRationalNumbersMathUnitUsingGoogle-1.pdf',
 '7thGradeMathAngleRelationshipsandTrianglesUnit7G27G5-1 (1).zip',
 '7thGradeMathAngleRelationshipsandTrianglesUnit7G27G5-1 (2).zip',
 '7thGradeMathAngleRelationshipsandTrianglesUnit7G27G5-1 (3).zip',
 '7thGradeMathAngleRelationshipsandTrianglesUnit7G27G5-1 (4).zip',
 '7thGradeMathAngleRelationshipsandTrianglesUnit7G27G5-1 (5).zip',
 '7thGradeMathAngleRelationshipsandTrianglesUnit7G27G5-1 (6).zip',
 '7thGradeMathAngleRelationshipsandTrianglesUnit7G27G5-1 (7).zip',
 '7thGradeMathAngleRelationshipsandTrianglesUnit7G27G5-1 (8).zip',
 '7thGradeMathAngleRelationshipsandTrianglesUnit7G27G5-1.zip',
 '7thGradeMathCommonCoreTestPrepandReview-1.zip',
 '7thGradeMathGameDIGITALAnglesinGeometryDistanceLearning-1.zip',
 '7thGradeMathGameDIGITALAreaCircumferenceDistanceLearning-1.zip',
 '7thGradeMathGameDIGITALCentralTendencyDistanceLearning-1.zip',
 '7thGradeMathGameDIGITALInequalitiesDistanceLearning-1.zip',
 '7thGradeMathGameDIGITALMultiStepEquationsDistanceLearning-1.zip',
 '7thGradeMathGameDIGITALOneTwoStepEquationsDistanceLearning-1.zip',
 '7thGradeMathGameDIGITALOperationswithRationalNumbersDistanceLearning-1.zip',
 '7thGradeMathGameDIGITALProbabilityDistanceLearning-1.zip',
 '7thGradeMathGameDIGITALProportionsDistanceLearning-1.zip',
 '7thGradeMathGameDIGITALVolumeSurfaceAreaDistanceLearning-1.zip',
 '7thGradeMathGraphingFunctionsSlopeandConstantofProportionalityGOOGLE-1.pdf',
 '7thGradeProbabilityandStatisticsUnitUsingGoogle-1.pdf',
 '7thGradeRatiosProportionsPercentandSimilarFiguresUnitUsingGoogle-1.pdf',
 '7thGradeStatisticsNotesRandomSamplingandComparingPopulations-1 (1).zip',
 '7thGradeStatisticsNotesRandomSamplingandComparingPopulations-1.zip',
 '7_Lookup_Functions.xlsx',
 '8.1 Notes -Adding & Subtracting Polynomials.pdf',
 '8.2 Notes -Multiplying a Monomial by a Polynomial.pdf',
 '8.3 Notes -Multiplying a Monomial by a Polynomial AND Quiz 8.1-8.2.pdf',
 '8.4 Notes -Special Products and Spiral Review Quiz #8.pdf',
 '8.5 (Part 1) Notes -Using the Distributive Property (GCF).pdf',
 '8.5 (Part 2) Notes -Using the Distributive Property (Grouping).pdf',
 '8EE1IntrototheRulesforZeroandNegativeExponentspowerpoint-1 (1).pptx',
 '8EE1IntrototheRulesforZeroandNegativeExponentspowerpoint-1.pptx',
 '8EE1IntrotoZeroandNegativeExponentspowerpoint-1.pptx',
 '8th Grade Math Ultimate Bundle {Paper + Digital} Math 8 Curriculum Resources.zip',
 '8_Text_Functions.xlsx',
 'A Day Math Lesson Plans (1).html',
 'A Day Math Lesson Plans.html',
 "A'leah W. ESQ (1).xlsx",
 "A'leah W. ESQ (2).xlsx",
 "A'leah W. ESQ (3).xlsx",
 "A'leah W. ESQ (4).xlsx",
 "A'leah W. ESQ (5).xlsx",
 "A'leah W. ESQ.xlsx",
 'AddSubtractMultiplyDivideIntegersWordProblemsSmartboardLesson-1 (1).notebook',
 'AddSubtractMultiplyDivideIntegersWordProblemsSmartboardLesson-1 (2).notebook',
 'AddSubtractMultiplyDivideIntegersWordProblemsSmartboardLesson-1.notebook',
 'Adult Freestyle Form.docx',
 'Advance Tableau Video (1).twb',
 'Advance Tableau Video (2).twb',
 'Advance Tableau Video (3).twb',
 'Advance Tableau Video (4).twb',
 'Advance Tableau Video (5).twb',
 'Advance Tableau Video (6).twb',
 'Advance Tableau Video.twb',
 'Advance Tableau Wireframe (1).png',
 'Advance Tableau Wireframe (2).png',
 'Advance Tableau Wireframe.png',
 'Alg I Cp  (Fri.) 3-20-2020.pdf',
 'Alg I Cp  (Thurs) 3-19-2020.pdf',
 'Alg I Cp  Wed 3-18-20.pdf',
 'Alg I Cp Wed 3-18-20 (Work shown).pdf',
 'Algebraic Expressions Review (1) (1).notebook',
 'Algebraic Expressions Review (1).notebook',
 'Algebraic Expressions Review.notebook',
 'Algebraic Expressions Study Guide (1).docx',
 'Algebraic Expressions Study Guide (2).docx',
 'Algebraic Expressions Study Guide (3).docx',
 'Algebraic Expressions Study Guide.docx',
 'Anaconda3-2026.07-1-Windows-x86_64.exe',
 'Andriod Scan documents (1).pdf',
 'Andriod Scan documents (2).pdf',
 'Andriod Scan documents.pdf',
 'Angie Copy of Invention Graphic Organizer.pdf',
 'Angles and Triangles Digital Math Activity Bundle _ 7th Grade Math (1).zip',
 'Angles and Triangles Digital Math Activity Bundle _ 7th Grade Math (2).zip',
 'Angles and Triangles Digital Math Activity Bundle _ 7th Grade Math (3).zip',
 'Angles and Triangles Digital Math Activity Bundle _ 7th Grade Math (4).zip',
 'Angles and Triangles Digital Math Activity Bundle _ 7th Grade Math (5).zip',
 'Angles and Triangles Digital Math Activity Bundle _ 7th Grade Math (6).zip',
 'Angles and Triangles Digital Math Activity Bundle _ 7th Grade Math (7).zip',
 'Angles and Triangles Digital Math Activity Bundle _ 7th Grade Math (8).zip',
 'Angles and Triangles Digital Math Activity Bundle _ 7th Grade Math.zip',
 'AnglesTrianglesUnitAngleRelationshipsGuidedNotesfor7thGradeMath-1.zip',
 'Annual Contract Evaluation Letter - 2021-2022.pdf',
 'Annual_Anniversary Statement (1).pdf',
 'Annual_Anniversary Statement (2).pdf',
 'Annual_Anniversary Statement.pdf',
 'applicationdocs1transcripts.zip',
 'applicationdocs2praxismbawpuscteachingcert.zip',
 'ApproximatingSquareRoots-1 (1).pdf',
 'ApproximatingSquareRoots-1.pdf',
 'archive (1).zip',
 'archive (2).zip',
 'archive.zip',
 'Area of Composite Figures.docx',
 'AreaandCircumferenceofaCircleActivityBreakoutEscapeRoomGeometryGame-1 (1).pdf',
 'AreaandCircumferenceofaCircleActivityBreakoutEscapeRoomGeometryGame-1 (2).pdf',
 'AreaandCircumferenceofaCircleActivityBreakoutEscapeRoomGeometryGame-1 (3).pdf',
 'AreaandCircumferenceofaCircleActivityBreakoutEscapeRoomGeometryGame-1 (4).pdf',
 'AreaandCircumferenceofaCircleActivityBreakoutEscapeRoomGeometryGame-1.pdf',
 'AreaandCircumferenceofCirclesActivityMystery-1.zip',
 'AreaCircumferenceofCirclesDigitalEscapeRoomPerfectforPiDay-2 (1).pdf',
 'AreaCircumferenceofCirclesDigitalEscapeRoomPerfectforPiDay-2.pdf',
 'ATT00001',
 'ATT00001 (1)',
 'Awards-1.pdf',
 'a_210311110333422.html',
 'Background Check Release Form.docx',
 'BacktoSchoolMathActivityforUpperGrades-1 (1).pdf',
 'BacktoSchoolMathActivityforUpperGrades-1.pdf',
 'Basic_Dashboard_Sketch_Wireframe (1).png',
 'Basic_Dashboard_Sketch_Wireframe.png',
 'Blank Limbo Gameboard .pdf',
 'Brother Properties.pdf',
 'B_Day_MATH_6th_Period.csv',
 'Castilla .JPG',
 'Castilla day 4.pdf',
 'Castilla Day 9.pdf',
 'CASTILLA DIGITAL Musculoskeletal & Nervous System Quiz Paper Version Digital.docx',
 'CASTILLA DIGITAL Musculoskeletal & Nervous System Quiz Paper Version Digital.pdf',
 'Castilla Essay #2  GT course (Acceleration).docx',
 'Castilla Expanding and Factoring Review 2 (1).docx',
 'Castilla Expanding and Factoring Review 2.docx',
 'Castilla Independent vs Dependent Probability.pptx',
 'Castilla Lesson Plans for (Thurs.) 3_25_21.docx',
 'Castilla Lesson Plans for (Wed) 3_24_21.docx',
 'Castilla Populations and Samples.pdf',
 'Castilla Substitute Lesson Plans for (Tues. 061521) (1).docx',
 'Castilla Substitute Lesson Plans for (Tues. 061521).docx',
 'Castilla Substitute Lesson Plans for (Wed. 061621) (1).docx',
 'Castilla Substitute Lesson Plans for (Wed. 061621).docx',
 'Castilla1 Cover Letter 2025.docx',
 'CastillaLinkedIn.JPG',
 'castillapassportphotos2.zip',
 'Castilla_12-11-20.docx',
 'Chapter 6 Review  -Systems of Equations.docx',
 'Chapter 6 Review  -Systems of Equations.pdf',
 'Chapter 8 -Part 1 Test  (Alg 1 Cp).pdf',
 'Chapter 8-Part 1 Test (Updated).pdf',
 'Chapter 8-Part 1 Test ANSWER KEY (Updated).pdf',
 'Chapter 8-Part 1 Test ANSWER KEY.pdf',
 'Chapter 8-Part 1 Test RETAKE (Updated).pdf',
 'Chapter 8-Part 1 Test RETAKE ANSWER KEY (Updated).pdf',
 'Chapter 8-Part 1 Test RETAKE ANSWER KEY.pdf',
 'Chapter 8-Part 1 Test RETAKE.pdf',
 'Chapter 8-Part 1 Test.pdf',
 'ChessHelpSheet-1.pdf',
 'ChromeSetup (1).exe',
 'ChromeSetup (2).exe',
 'ChromeSetup (3).exe',
 'ChromeSetup.exe',
 'circle review.docx',
 'Circles -Area & Circumference.pdf',
 'Circles Review (1).docx',
 'Circles Review Guide M7.docx',
 'Circles Review.docx',
 'CircumferenceandAreaofCirclesDIGITALActivityforGoogleDistanceLearning-1.zip',
 'CircumferenceofCirclesWorksheetMazeActivity-1.pdf',
 'Claude CoverLetter Template.docx',
 'Claude Resume Template.docx',
 'Combining Integers (1).notebook',
 'Combining Integers (2).notebook',
 'Combining Integers (3).notebook',
 'Combining Integers (4).notebook',
 'Combining Integers (5).notebook',
 'Combining Integers.notebook',
 'Complex Fractions (1).notebook',
 'Complex Fractions (2).notebook',
 'Complex Fractions.notebook',
 'ComplexFractionsMathLib-1 (1).zip',
 'ComplexFractionsMathLib-1.zip',
 'ComplexFractionsNotesHomeworkWarmUpsExitTickets-1 (1).pdf',
 'ComplexFractionsNotesHomeworkWarmUpsExitTickets-1 (2).pdf',
 'ComplexFractionsNotesHomeworkWarmUpsExitTickets-1.pdf',
 'Copy of  Blue Purple Futuristic Project Manager LinkedIn Banner .png',
 'Copy of Exercise 1_ Identify Your Top 5 Transferable Skills.docx',
 'Copy of Teacher Supply Expenditure Form (004) (1).xlsx',
 'Copy of Teacher Supply Expenditure Form (004).xlsx',
 'Copy of Yellow Monochrome Photo LinkedIn Banner (1).zip',
 'Copy of Yellow Monochrome Photo LinkedIn Banner (2).zip',
 'Copy of Yellow Monochrome Photo LinkedIn Banner (3).zip',
 'Copy of Yellow Monochrome Photo LinkedIn Banner (4)',
 'Copy of Yellow Monochrome Photo LinkedIn Banner (4).zip',
 'Copy of Yellow Monochrome Photo LinkedIn Banner.zip',
 'COVID Notification of a Postive Case in the School Setting Letter Final 2020.docx',
 'Create a Creature Project.pdf',
 'Create a Seating Chart (1).pptx',
 'Create a Seating Chart.pptx',
 'Crossrope _ Orders _ #666647 _ Shopify Plus.pdf',
 'CV012020NSCarolinaJMMSwMBC(Fort Mill).docx',
 'CV012024NSCarolinaFMSDwMBC.docx',
 'DAC2 Keyboard functions 1.pdf',
 'DAC2 Keyboard functions 2 (1).pdf',
 'DAC2 Keyboard functions 2.pdf',
 'DAC2 Spreadsheet Errors and Fixes (1).pdf',
 'DAC2 Spreadsheet Errors and Fixes (2).pdf',
 'DAC2 Spreadsheet Errors and Fixes.pdf',
 'DAC3-In-depth-guide_-SQL-best-practices.pdf',
 'Data Analysis & Probability Study Guide.pdf',
 'Data Career Launch Program Plan (1).docx',
 'Data Career Launch Program Plan.docx',
 'Data In Motion Situation Catalog (1).docx',
 'Data In Motion Situation Catalog (2).docx',
 'Data In Motion Situation Catalog (3)',
 'Data In Motion Situation Catalog (3).docx',
 'Data In Motion Situation Catalog (4).docx',
 'Data In Motion Situation Catalog (5).docx',
 'Data In Motion Situation Catalog.docx',
 'data.csv',
 'DataLemur SQL Interview and Problem Solving (1).pdf',
 'DataLemur SQL Interview and Problem Solving (2).pdf',
 'DataLemur SQL Interview and Problem Solving (3).pdf',
 'DataLemur SQL Interview and Problem Solving.pdf',
 'data_jobs_salary_all.xlsx',
 'data_jobs_salary_monthly (1).xlsx',
 'data_jobs_salary_monthly.xlsx',
 'Day 2 guided notes and practice (1).pdf',
 'Day 2 guided notes and practice.pdf',
 'Day 3 guided notes and practice.pdf',
 'Day 9 Foundations.pdf',
 'demo7thPopulationSamplesinaPowerPointPresentation1644325 (1).zip',
 'demo7thPopulationSamplesinaPowerPointPresentation1644325.zip',
 'demobts7thgradepreviewjpg (1).jpg',
 'demobts7thgradepreviewjpg.jpg',
 'demoDistanceLearningMathAreaandCircumferenceofCirclesPIXELARTGoogleSheets5590963.png',
 'demoEvaluatingExpressionsPIXELARTMadeforGoogleDrive5152353.png',
 'demoGettoKnowYouBINGO9723437.png',
 'demoMathCafeActivityPercentagesSalesTaxTip9305569.png',
 'demoProportionalLinearRelationshipsSlopeasUnitRateGuidedNotes8902773 (1).png',
 'demoProportionalLinearRelationshipsSlopeasUnitRateGuidedNotes8902773 (2).png',
 'demoProportionalLinearRelationshipsSlopeasUnitRateGuidedNotes8902773.png',
 'demoSamplesandPopulationsDigitalMathActivity7thGradeGoogleSlidesActivity6308364 (1).png',
 'demoSamplesandPopulationsDigitalMathActivity7thGradeGoogleSlidesActivity6308364.png',
 'demoWritingAlgebraicExpressionsforDistanceLearning5484132.jpeg',
 'demoWritingequationswithproportionalrelationships6196298.png',
 'desktop.ini',
 'DIM Academy Logo (1).png',
 'DIM Academy Logo.png',
 'DIM SQL Workshop Series Fall 2025.pptx',
 'DIM_SQL_Course_databasesetup (1).zip',
 'DIM_SQL_Course_databasesetup (2).zip',
 'DIM_SQL_Course_databasesetup.zip',
 'Direct deposit receipt (1).PDF',
 'Direct deposit receipt.PDF',
 'DirectDebitBillDueMarch25,2020_03-04-2020.pdf',
 'Directory.pdf',
 'DiscordSetup (1).exe',
 'DiscordSetup (2).exe',
 'DiscordSetup.exe',
 'DistributeandFactorLinearExpressionsDigitalActivityDistanceLearning-1.pdf',
 'dlz-trifold-greyscale-kp5sod (1).pdf',
 'dlz-trifold-greyscale-kp5sod.pdf',
 'DOC012820-01282020154635.pdf',
 'DOC020221-02022021113929.pdf',
 'DOC020222-02022022141250.pdf',
 'DOC031720-03172020120820.pdf',

In [4]:
[file for file in os.listdir("Downloads") if "watson" in file.lower()]

['watson_healthcare_modified2 (1).csv',
 'watson_healthcare_modified2 (2).csv',
 'watson_healthcare_modified2 (3).csv',
 'watson_healthcare_modified2 (4).csv',
 'watson_healthcare_modified2 (5).csv',
 'watson_healthcare_modified2.csv']

In [5]:
df = pd.read_csv("Downloads/watson_healthcare_modified2 (2).csv")

In [6]:
df.head()

,EmployeeID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,1313919,41,No,Travel_Rarely,1102,Cardiology,1,2,Life Sciences,1,...,1,80,0,8,0,1,6,4,0,5
1,1200302,49,No,Travel_Frequently,279,Maternity,8,1,Life Sciences,1,...,4,80,1,10,3,3,10,7,1,7
2,1060315,37,Yes,Travel_Rarely,1373,Maternity,2,2,Other,1,...,2,80,0,7,3,3,0,0,0,0
3,1272912,33,No,Travel_Frequently,1392,Maternity,3,4,Life Sciences,1,...,3,80,0,8,3,3,8,7,3,0
4,1414939,27,No,Travel_Rarely,591,Maternity,2,1,Medical,1,...,4,80,1,6,3,3,2,2,2,2

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1676 entries, 0 to 1675
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmployeeID                1676 non-null   int64
 1   Age                       1676 non-null   int64
 2   Attrition                 1676 non-null   str
 3   BusinessTravel            1676 non-null   str
 4   DailyRate                 1676 non-null   int64
 5   Department                1676 non-null   str
 6   DistanceFromHome          1676 non-null   int64
 7   Education                 1676 non-null   int64
 8   EducationField            1676 non-null   str
 9   EmployeeCount             1676 non-null   int64
 10  EnvironmentSatisfaction   1676 non-null   int64
 11  Gender                    1676 non-null   str
 12  HourlyRate                1676 non-null   int64
 13  JobInvolvement            1676 non-null   int64
 14  JobLevel                  1676 non-null   int64
 15  JobRole                   1676 non-null   str
 16  JobSatisfaction           1676 non-null   int64
 17  MaritalStatus             1676 non-null   str
 18  MonthlyIncome             1676 non-null   int64
 19  MonthlyRate               1676 non-null   int64
 20  NumCompaniesWorked        1676 non-null   int64
 21  Over18                    1676 non-null   str
 22  OverTime                  1676 non-null   str
 23  PercentSalaryHike         1676 non-null   int64
 24  PerformanceRating         1676 non-null   int64
 25  RelationshipSatisfaction  1676 non-null   int64
 26  StandardHours             1676 non-null   int64
 27  Shift                     1676 non-null   int64
 28  TotalWorkingYears         1676 non-null   int64
 29  TrainingTimesLastYear     1676 non-null   int64
 30  WorkLifeBalance           1676 non-null   int64
 31  YearsAtCompany            1676 non-null   int64
 32  YearsInCurrentRole        1676 non-null   int64
 33  YearsSinceLastPromotion   1676 non-null   int64
 34  YearsWithCurrManager      1676 non-null   int64
dtypes: int64(26), str(9)
memory usage: 550.9 KB

In [8]:
df.shape

(1676, 35)

In [9]:
df.columns

Index(['EmployeeID', 'Age', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome', 'Education', 'EducationField',
       'EmployeeCount', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'Shift',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='str')

In [10]:
df['Attrition'].value_counts()

Attrition
No     1477
Yes     199
Name: count, dtype: int64

In [11]:
attrition_rate = (df['Attrition'] == 'Yes').mean() * 100
attrition_rate

np.float64(11.873508353221956)

In [12]:
df.groupby('Department')['Attrition'].apply(lambda x: (x == 'Yes').mean() * 100)

Department
Cardiology    13.935970
Maternity     12.311558
Neurology      7.736390
Name: Attrition, dtype: float64

In [13]:
df['Department'].value_counts()

Department
Maternity     796
Cardiology    531
Neurology     349
Name: count, dtype: int64

In [14]:
df.groupby('Attrition')['Age'].mean()

Attrition
No     37.670278
Yes    30.899497
Name: Age, dtype: float64

In [15]:
df.groupby('Attrition')['Age'].describe()

            count       mean       std   min   25%   50%   75%   max
Attrition
No         1477.0  37.670278  8.865543  18.0  31.0  36.0  44.0  60.0
Yes         199.0  30.899497  8.860875  18.0  25.5  29.0  34.0  58.0

In [16]:
df.groupby('Gender')['Attrition'].apply(lambda x: (x == 'Yes').mean() * 100)

Gender
Female    12.684366
Male      11.322645
Name: Attrition, dtype: float64

In [17]:
df.groupby('Education')['Attrition'].apply(lambda x: (x == 'Yes').mean() * 100)

Education
1    13.775510
2    10.869565
3    13.587786
4    10.514541
5     1.785714
Name: Attrition, dtype: float64

In [18]:
from scipy.stats import chi2_contingency

gender_table = pd.crosstab(df['Gender'], df['Attrition'])
chi2, p_value, dof, expected = chi2_contingency(gender_table)

p_value

np.float64(0.4419454127111361)

In [19]:
education_table = pd.crosstab(df['Education'], df['Attrition'])
chi2, p_value, dof, expected = chi2_contingency(education_table)

p_value

np.float64(0.059555671404858734)

In [20]:
df.groupby('JobRole')['Attrition'].apply(lambda x: (x == 'Yes').mean() * 100)

JobRole
Admin              0.000000
Administrative     0.869565
Nurse             13.017032
Other             16.292135
Therapist          2.116402
Name: Attrition, dtype: float64

In [21]:
df['JobRole'].value_counts()

JobRole
Nurse             822
Other             534
Therapist         189
Administrative    115
Admin              16
Name: count, dtype: int64

In [22]:
jobrole_table = pd.crosstab(df['JobRole'], df['Attrition'])
chi2, p_value, dof, expected = chi2_contingency(jobrole_table)

p_value

np.float64(7.58311282316894e-09)

In [23]:
df.groupby('JobSatisfaction')['Attrition'].apply(lambda x: (x == 'Yes').mean() * 100)

JobSatisfaction
1    15.805471
2    13.548387
3    11.834320
4     8.490566
Name: Attrition, dtype: float64

In [24]:
satisfaction_table = pd.crosstab(df['JobSatisfaction'], df['Attrition'])
chi2, p_value, dof, expected = chi2_contingency(satisfaction_table)

p_value

np.float64(0.009352917864491304)

In [25]:
df.groupby('DistanceFromHome')['Attrition'].apply(lambda x: (x == 'Yes').mean() * 100)

DistanceFromHome
1      8.786611
2      8.713693
3     11.458333
4      5.797101
5     13.157895
6     11.111111
7      7.368421
8     10.112360
9     15.053763
10     8.080808
11     6.060606
12    15.000000
13    18.181818
14    22.727273
15    13.793103
16    15.789474
17    21.739130
18    10.714286
19    14.814815
20    11.111111
21     9.090909
22    25.000000
23    18.181818
24    41.176471
25    27.586207
26    17.857143
27    16.666667
28     3.703704
29    12.121212
Name: Attrition, dtype: float64

In [26]:
distance_table = pd.crosstab(df['DistanceFromHome'], df['Attrition'])
chi2, p_value, dof, expected = chi2_contingency(distance_table)

p_value

np.float64(0.00026172023993134254)

In [27]:
df.groupby('WorkLifeBalance')['Attrition'].apply(lambda x: (x == 'Yes').mean() * 100)

WorkLifeBalance
1    26.666667
2    14.025974
3     9.727626
4    12.138728
Name: Attrition, dtype: float64

In [28]:
balance_table = pd.crosstab(df['WorkLifeBalance'], df['Attrition'])
chi2, p_value, dof, expected = chi2_contingency(balance_table)

p_value

np.float64(1.4980223398086616e-05)

In [29]:
df.groupby('PerformanceRating')['Attrition'].apply(lambda x: (x == 'Yes').mean() * 100)

PerformanceRating
3    11.727528
4    12.698413
Name: Attrition, dtype: float64

In [30]:
performance_table = pd.crosstab(df['PerformanceRating'], df['Attrition'])
chi2, p_value, dof, expected = chi2_contingency(performance_table)

p_value

np.float64(0.7387227176552524)

In [31]:
df.groupby('Attrition')['MonthlyIncome'].mean()

Attrition
No     6852.301963
Yes    4024.246231
Name: MonthlyIncome, dtype: float64

In [32]:
df.groupby('Attrition')['MonthlyIncome'].describe()

,count,mean,std,min,25%,50%,75%,max
Attrition,,,,,,,,
No,1477.0,6852.301963,4810.634808,1051.0,3294.0,5204.0,8858.0,19999.0
Yes,199.0,4024.246231,3089.287935,1009.0,2304.5,2741.0,4782.0,19859.0

In [33]:
from scipy.stats import ttest_ind

stayed = df[df['Attrition'] == 'No']['MonthlyIncome']
left = df[df['Attrition'] == 'Yes']['MonthlyIncome']

t_stat, p_value = ttest_ind(stayed, left, equal_var=False)

p_value

np.float64(4.518906398417315e-25)

In [34]:
df.groupby('YearsAtCompany')['Attrition'].apply(lambda x: (x == 'Yes').mean() * 100)

YearsAtCompany
0     39.130435
1     30.256410
2     20.547945
3     11.184211
4     11.666667
5      8.675799
6      5.813953
7      9.615385
8      6.451613
9      3.191489
10     8.029197
11     2.702703
12     0.000000
13     0.000000
14     5.000000
15     8.695652
16     0.000000
17     0.000000
18     0.000000
19     7.142857
20     0.000000
21     0.000000
22     0.000000
23    50.000000
24     0.000000
25     0.000000
26     0.000000
27     0.000000
29     0.000000
30     0.000000
31    33.333333
32     0.000000
33     0.000000
34     0.000000
36     0.000000
37     0.000000
40     0.000000
Name: Attrition, dtype: float64

In [35]:
df['YearsAtCompany'].value_counts().sort_index()

YearsAtCompany
0      46
1     195
2     146
3     152
4     120
5     219
6      86
7     104
8      93
9      94
10    137
11     37
12     17
13     28
14     20
15     23
16     12
17     12
18     13
19     14
20     32
21     17
22     19
23      2
24      7
25      5
26      4
27      2
29      2
30      1
31      3
32      3
33      6
34      1
36      2
37      1
40      1
Name: count, dtype: int64

In [36]:
tenure_table = pd.crosstab(df['YearsAtCompany'], df['Attrition'])
chi2, p_value, dof, expected = chi2_contingency(tenure_table)

p_value

np.float64(5.4853064231239483e-17)

In [37]:
df.groupby('YearsSinceLastPromotion')['Attrition'].apply(lambda x: (x == 'Yes').mean() * 100)

YearsSinceLastPromotion
0     16.060606
1      9.203980
2     14.516129
3      9.090909
4      3.174603
5      2.000000
6      4.878049
7     13.253012
8      0.000000
9     10.000000
10    28.571429
11     3.333333
12     0.000000
13     8.333333
14    11.111111
15     0.000000
Name: Attrition, dtype: float64

In [38]:
promotion_table = pd.crosstab(df['YearsSinceLastPromotion'], df['Attrition'])
chi2, p_value, dof, expected = chi2_contingency(promotion_table)

p_value

np.float64(0.0011388067616569014)

In [39]:
df.groupby('YearsInCurrentRole')['Attrition'].apply(lambda x: (x == 'Yes').mean() * 100)

YearsInCurrentRole
0     26.739927
1     16.393443
2     14.976959
3      6.164384
4     10.526316
5      2.325581
6      2.325581
7      8.171206
8      1.923077
9      5.063291
10     0.000000
11     0.000000
12     0.000000
13     0.000000
14     0.000000
15    11.111111
16     0.000000
17     0.000000
18     0.000000
Name: Attrition, dtype: float64

In [40]:
current_role_table = pd.crosstab(df['YearsInCurrentRole'], df['Attrition'])
chi2, p_value, dof, expected = chi2_contingency(current_role_table)

p_value

np.float64(1.1238737536813488e-14)

In [41]:
df.groupby('Attrition')['TrainingTimesLastYear'].mean()

Attrition
No     2.831415
Yes    2.613065
Name: TrainingTimesLastYear, dtype: float64

In [42]:
training_stayed = df[df['Attrition'] == 'No']['TrainingTimesLastYear']
training_left = df[df['Attrition'] == 'Yes']['TrainingTimesLastYear']

t_stat, p_value = ttest_ind(training_stayed, training_left, equal_var=False)

p_value

np.float64(0.025367184674005096)

In [43]:
df.columns.tolist()

['EmployeeID',
 'Age',
 'Attrition',
 'BusinessTravel',
 'DailyRate',
 'Department',
 'DistanceFromHome',
 'Education',
 'EducationField',
 'EmployeeCount',
 'EnvironmentSatisfaction',
 'Gender',
 'HourlyRate',
 'JobInvolvement',
 'JobLevel',
 'JobRole',
 'JobSatisfaction',
 'MaritalStatus',
 'MonthlyIncome',
 'MonthlyRate',
 'NumCompaniesWorked',
 'Over18',
 'OverTime',
 'PercentSalaryHike',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'StandardHours',
 'Shift',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager']

In [44]:
df.groupby('NumCompaniesWorked')['Attrition'].apply(lambda x: (x == 'Yes').mean() * 100)

NumCompaniesWorked
0     8.968610
1    15.474210
2     5.780347
3     5.555556
4     7.051282
5    17.142857
6    18.987342
7    19.047619
8     7.843137
9    13.559322
Name: Attrition, dtype: float64

In [45]:
companies_table = pd.crosstab(df['NumCompaniesWorked'], df['Attrition'])
chi2, p_value, dof, expected = chi2_contingency(companies_table)
p_value

np.float64(3.259510514390069e-05)

In [46]:
department_attrition = pd.crosstab(
    df["Department"],
    df["Attrition"],
    normalize="index"
) * 100

department_attrition

Attrition          No        Yes
Department
Cardiology  86.064030  13.935970
Maternity   87.688442  12.311558
Neurology   92.263610   7.736390

In [47]:
import pandas as pd

In [48]:
department_attrition = pd.crosstab(
    df["Department"],
    df["Attrition"],
    normalize="index"
) * 100

department_attrition

Attrition          No        Yes
Department
Cardiology  86.064030  13.935970
Maternity   87.688442  12.311558
Neurology   92.263610   7.736390

In [49]:
df = pd.read_csv("Downloads/watson_healthcare_modified2 (2).csv")

In [50]:
df.shape

(1676, 35)

In [51]:
department_attrition = pd.crosstab(
    df["Department"],
    df["Attrition"],
    normalize="index"
) * 100

department_attrition

Attrition          No        Yes
Department
Cardiology  86.064030  13.935970
Maternity   87.688442  12.311558
Neurology   92.263610   7.736390

In [52]:
job_level_attrition = pd.crosstab(
    df["JobLevel"],
    df["Attrition"],
    normalize="index"
) * 100

job_level_attrition

Attrition         No        Yes
JobLevel
1          77.133655  22.866345
2          94.389439   5.610561
3          92.682927   7.317073
4          97.540984   2.459016
5          97.530864   2.469136

In [53]:
worklife_attrition = pd.crosstab(
    df["WorkLifeBalance"],
    df["Attrition"],
    normalize="index"
) * 100

worklife_attrition

Attrition               No        Yes
WorkLifeBalance
1                73.333333  26.666667
2                85.974026  14.025974
3                90.272374   9.727626
4                87.861272  12.138728

In [54]:
df.groupby("Attrition")["MonthlyIncome"].agg(["mean", "median"])

                  mean  median
Attrition
No         6852.301963  5204.0
Yes        4024.246231  2741.0

In [55]:
from scipy.stats import ttest_ind

stayed = df[df["Attrition"] == "No"]["MonthlyIncome"]
left = df[df["Attrition"] == "Yes"]["MonthlyIncome"]

t_stat, p_value = ttest_ind(stayed, left, equal_var=False)

t_stat, p_value

(np.float64(11.211619222943114), np.float64(4.518906398417315e-25))

In [56]:
df["Attrition"].value_counts(normalize=True) * 100

Attrition
No     88.126492
Yes    11.873508
Name: proportion, dtype: float64

In [57]:
overtime_attrition = pd.crosstab(
    df["OverTime"],
    df["Attrition"],
    normalize="index"
) * 100

overtime_attrition

Attrition         No        Yes
OverTime
No         95.000000   5.000000
Yes        70.798319  29.201681

In [58]:
from scipy.stats import chi2_contingency

overtime_table = pd.crosstab(
    df["OverTime"],
    df["Attrition"]
)

chi2, p_value, dof, expected = chi2_contingency(overtime_table)

chi2, p_value

(np.float64(188.46831700066724), np.float64(6.865486230870457e-43))

In [59]:
worklife_table = pd.crosstab(
    df["WorkLifeBalance"],
    df["Attrition"]
)

chi2, p_value, dof, expected = chi2_contingency(worklife_table)

chi2, p_value

(np.float64(25.062856995853586), np.float64(1.4980223398086616e-05))

In [60]:
overtime_worklife = pd.crosstab(
    [df["OverTime"], df["WorkLifeBalance"]],
    df["Attrition"],
    normalize="index"
) * 100

overtime_worklife

Attrition                        No        Yes
OverTime WorkLifeBalance
No       1                78.787879  21.212121
         2                94.382022   5.617978
         3                96.994536   3.005464
         4                93.333333   6.666667
Yes      1                58.333333  41.666667
         2                66.949153  33.050847
         3                73.648649  26.351351
         4                68.421053  31.578947

In [61]:
pd.crosstab(
    [df["OverTime"], df["WorkLifeBalance"]],
    df["Attrition"]
)

Attrition                  No  Yes
OverTime WorkLifeBalance
No       1                 52   14
         2                252   15
         3                710   22
         4                126    9
Yes      1                 14   10
         2                 79   39
         3                218   78
         4                 26   12

In [62]:
summary = {
    "Overall Attrition": "11.87%",
    "Overtime Attrition": "29.20% vs. 5.00% without overtime",
    "Lowest Work-Life Balance Attrition": "26.67%",
    "Job Level 1 Attrition": "22.87%",
    "Monthly Income": "$4,024 mean for employees who left vs. $6,852 for employees who stayed"
}

for finding, result in summary.items():
    print(f"{finding}: {result}")

Overall Attrition: 11.87%
Overtime Attrition: 29.20% vs. 5.00% without overtime
Lowest Work-Life Balance Attrition: 26.67%
Job Level 1 Attrition: 22.87%
Monthly Income: $4,024 mean for employees who left vs. $6,852 for employees who stayed

In [63]:
df.loc[df['Attrition'] == 'Yes', 'MonthlyIncome'].mean()

np.float64(4024.246231155779)

In [64]:
# Finding 1: Overall Attrition Rate
(df['Attrition'] == 'Yes').mean() * 100

np.float64(11.873508353221956)

In [65]:
# Finding 2: Attrition by Department
df.groupby('Department')['Attrition'].apply(
    lambda x: (x == 'Yes').mean() * 100
)

Department
Cardiology    13.935970
Maternity     12.311558
Neurology      7.736390
Name: Attrition, dtype: float64

In [66]:
# Finding 3: Overtime and Attrition
pd.crosstab(
    df['OverTime'],
    df['Attrition'],
    normalize='index'
) * 100

Attrition         No        Yes
OverTime
No         95.000000   5.000000
Yes        70.798319  29.201681

In [67]:
# Finding 4: Overtime and Work-Life Balance
pd.crosstab(
    [df['OverTime'], df['WorkLifeBalance']],
    df['Attrition'],
    normalize='index'
) * 100

Attrition                        No        Yes
OverTime WorkLifeBalance
No       1                78.787879  21.212121
         2                94.382022   5.617978
         3                96.994536   3.005464
         4                93.333333   6.666667
Yes      1                58.333333  41.666667
         2                66.949153  33.050847
         3                73.648649  26.351351
         4                68.421053  31.578947

In [68]:
# Finding 5: Work-Life Balance and Attrition
df.groupby('WorkLifeBalance')['Attrition'].apply(
    lambda x: (x == 'Yes').mean() * 100
)

WorkLifeBalance
1    26.666667
2    14.025974
3     9.727626
4    12.138728
Name: Attrition, dtype: float64

In [69]:
# Finding 6: Job Level and Attrition
pd.crosstab(
    df['JobLevel'],
    df['Attrition'],
    normalize='index'
) * 100

Attrition         No        Yes
JobLevel
1          77.133655  22.866345
2          94.389439   5.610561
3          92.682927   7.317073
4          97.540984   2.459016
5          97.530864   2.469136

In [70]:
# Finding 7: Monthly Income and Attrition
df.groupby('Attrition')['MonthlyIncome'].agg(['mean', 'median'])

                  mean  median
Attrition
No         6852.301963  5204.0
Yes        4024.246231  2741.0